"""App-issued email verification codes.

These codes are generated by this backend and emailed through Resend, so
signup verification does not depend on the Supabase mailer template or its
built-in email rate limit. Only a hash of each code is stored, so a database
read cannot be replayed as a valid code.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Integer, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import GUID, Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class EmailVerificationCode(Base):
    __tablename__ = "email_verification_codes"

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    code_hash: Mapped[str] = mapped_column(Text, nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False
    )
    # Set once the code is used or superseded; only NULL rows are live.
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
